# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: Linux

  pool:
    vmImage: 'ubuntu-22.04'

  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
      node_11_x:
        node_version: 11.x

  steps:
  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm test
    displayName: 'exec test'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: ./test-results.xml
      testRunTitle: 'test result'

- job: Windows

  pool:
    vmImage: 'windows-2022'

  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
      node_11_x:
        node_version: 11.x

  steps:
  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm test
    displayName: 'exec test'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: ./test-results.xml
      testRunTitle: 'test result'
